package Elyas.LssTestSheets.model;

public enum TestSheetProperties {
	INCOMPLETE_INST_ITEMS, INCOMPLETE_EXAM_ITEMS, PASSED_RESULT, FAILED_RESULT, INCLUDE_BARCODES, DOUBLE_SIDED, TOTAL_PASS_FAIL, INCLUDE_PAGE_NUMBERS, GENERATE_SINGLE_FILE, FLATTEN
}
